/**
 * Comprehensive list of languages for LinguaLink
 * ISO 639-1 codes with native names and English names
 */

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag?: string;
}

export const languages: readonly Language[] = [
  { code: 'aa', name: 'Afar', nativeName: 'Afaraf' },
  { code: 'ab', name: 'Abkhaz', nativeName: 'Аҧсуа' },
  { code: 'ae', name: 'Avestan', nativeName: 'avesta' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans' },
  { code: 'ak', name: 'Akan', nativeName: 'Akan' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ' },
  { code: 'an', name: 'Aragonese', nativeName: 'Aragonés' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'as', name: 'Assamese', nativeName: 'অসমীয়া' },
  { code: 'av', name: 'Avaric', nativeName: 'авар мацӀ' },
  { code: 'ay', name: 'Aymara', nativeName: 'aymar aru' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'azərbaycan dili' },
  { code: 'ba', name: 'Bashkir', nativeName: 'башҡорт теле' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'български език', flag: '🇧🇬' },
  { code: 'bh', name: 'Bihari', nativeName: 'भोजपुरी' },
  { code: 'bi', name: 'Bislama', nativeName: 'Bislama' },
  { code: 'bm', name: 'Bambara', nativeName: 'bamanankan' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'bo', name: 'Tibetan', nativeName: 'བོད་ཡིག' },
  { code: 'br', name: 'Breton', nativeName: 'brezhoneg' },
  { code: 'bs', name: 'Bosnian', nativeName: 'bosanski jezik' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català' },
  { code: 'ce', name: 'Chechen', nativeName: 'нохчийн мотт' },
  { code: 'ch', name: 'Chamorro', nativeName: 'Chamoru' },
  { code: 'co', name: 'Corsican', nativeName: 'corsu' },
  { code: 'cr', name: 'Cree', nativeName: 'ᓀᐦᐃᔭᐍᐏᐣ' },
  { code: 'cs', name: 'Czech', nativeName: 'česky', flag: '🇨🇿' },
  { code: 'cu', name: 'Church Slavonic', nativeName: 'ѩзыкъ словѣньскъ' },
  { code: 'cv', name: 'Chuvash', nativeName: 'чӑваш чӗлхи' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg' },
  { code: 'da', name: 'Danish', nativeName: 'dansk', flag: '🇩🇰' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'dv', name: 'Divehi', nativeName: 'ދިވެހި' },
  { code: 'dz', name: 'Dzongkha', nativeName: 'རྫོང་ཁ' },
  { code: 'ee', name: 'Ewe', nativeName: 'Eʋegbe' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', flag: '🇬🇷' },
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'et', name: 'Estonian', nativeName: 'eesti', flag: '🇪🇪' },
  { code: 'eu', name: 'Basque', nativeName: 'euskara' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', flag: '🇮🇷' },
  { code: 'ff', name: 'Fula', nativeName: 'Fulfulde' },
  { code: 'fi', name: 'Finnish', nativeName: 'suomi', flag: '🇫🇮' },
  { code: 'fj', name: 'Fijian', nativeName: 'vosa Vakaviti' },
  { code: 'fo', name: 'Faroese', nativeName: 'føroyskt' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'fy', name: 'Western Frisian', nativeName: 'Frysk' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', flag: '🇮🇪' },
  { code: 'gd', name: 'Gaelic', nativeName: 'Gàidhlig' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego' },
  { code: 'gn', name: 'Guaraní', nativeName: 'Avañeẽ' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'gv', name: 'Manx', nativeName: 'Gaelg' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', flag: '🇮🇱' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ho', name: 'Hiri Motu', nativeName: 'Hiri Motu' },
  { code: 'hr', name: 'Croatian', nativeName: 'hrvatski', flag: '🇭🇷' },
  { code: 'ht', name: 'Haitian', nativeName: 'Kreyòl ayisyen' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', flag: '🇭🇺' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն' },
  { code: 'hz', name: 'Herero', nativeName: 'Otjiherero' },
  { code: 'ia', name: 'Interlingua', nativeName: 'Interlingua' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'ie', name: 'Interlingue', nativeName: 'Interlingue' },
  { code: 'ig', name: 'Igbo', nativeName: 'Igbo' },
  { code: 'ii', name: 'Sichuan Yi', nativeName: 'ꆇꉙ' },
  { code: 'ik', name: 'Inupiaq', nativeName: 'Iñupiaq' },
  { code: 'io', name: 'Ido', nativeName: 'Ido' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', flag: '🇮🇸' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'iu', name: 'Inuktitut', nativeName: 'ᐃᓄᒃᑎᑐᑦ' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'jv', name: 'Javanese', nativeName: 'basa Jawa' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული' },
  { code: 'kg', name: 'Kongo', nativeName: 'KiKongo' },
  { code: 'ki', name: 'Kikuyu', nativeName: 'Gĩkũyũ' },
  { code: 'kj', name: 'Kwanyama', nativeName: 'Kuanyama' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі' },
  { code: 'kl', name: 'Kalaallisut', nativeName: 'kalaallisut' },
  { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'kr', name: 'Kanuri', nativeName: 'Kanuri' },
  { code: 'ks', name: 'Kashmiri', nativeName: 'कश्मीरी' },
  { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî' },
  { code: 'kv', name: 'Komi', nativeName: 'коми кыв' },
  { code: 'kw', name: 'Cornish', nativeName: 'Kernewek' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'кыргыз тили' },
  { code: 'la', name: 'Latin', nativeName: 'latine' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch' },
  { code: 'lg', name: 'Luganda', nativeName: 'Luganda' },
  { code: 'li', name: 'Limburgish', nativeName: 'Limburgs' },
  { code: 'ln', name: 'Lingala', nativeName: 'Lingála' },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'lietuvių kalba', flag: '🇱🇹' },
  { code: 'lu', name: 'Luba-Katanga', nativeName: 'Luba-Katanga' },
  { code: 'lv', name: 'Latvian', nativeName: 'latviešu valoda', flag: '🇱🇻' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy fiteny' },
  { code: 'mh', name: 'Marshallese', nativeName: 'Kajin M̧ajeļ' },
  { code: 'mi', name: 'Māori', nativeName: 'te reo Māori' },
  { code: 'mk', name: 'Macedonian', nativeName: 'македонски јазик' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'mn', name: 'Mongolian', nativeName: 'монгол' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', flag: '🇲🇾' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti' },
  { code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ' },
  { code: 'na', name: 'Nauru', nativeName: 'Ekakairũ Naoero' },
  { code: 'nb', name: 'Norwegian Bokmål', nativeName: 'Norsk bokmål', flag: '🇳🇴' },
  { code: 'nd', name: 'North Ndebele', nativeName: 'isiNdebele' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली' },
  { code: 'ng', name: 'Ndonga', nativeName: 'Owambo' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', flag: '🇳🇱' },
  { code: 'nn', name: 'Norwegian Nynorsk', nativeName: 'Norsk nynorsk' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', flag: '🇳🇴' },
  { code: 'nr', name: 'South Ndebele', nativeName: 'isiNdebele' },
  { code: 'nv', name: 'Navajo', nativeName: 'Diné bizaad' },
  { code: 'ny', name: 'Chichewa', nativeName: 'chiCheŵa' },
  { code: 'oc', name: 'Occitan', nativeName: 'Occitan' },
  { code: 'oj', name: 'Ojibwe', nativeName: 'ᐊᓂᔑᓈᐯᒧᐎᓐ' },
  { code: 'om', name: 'Oromo', nativeName: 'Afaan Oromoo' },
  { code: 'or', name: 'Oriya', nativeName: 'ଓଡ଼ିଆ' },
  { code: 'os', name: 'Ossetian', nativeName: 'ирон æвзаг' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'pi', name: 'Pāli', nativeName: 'पाऴि' },
  { code: 'pl', name: 'Polish', nativeName: 'polski', flag: '🇵🇱' },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  { code: 'qu', name: 'Quechua', nativeName: 'Runa Simi' },
  { code: 'rm', name: 'Romansh', nativeName: 'rumantsch grischun' },
  { code: 'rn', name: 'Kirundi', nativeName: 'kiRundi' },
  { code: 'ro', name: 'Romanian', nativeName: 'română', flag: '🇷🇴' },
  { code: 'ru', name: 'Russian', nativeName: 'русский язык', flag: '🇷🇺' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda' },
  { code: 'sa', name: 'Sanskrit', nativeName: 'संस्कृतम्' },
  { code: 'sc', name: 'Sardinian', nativeName: 'sardu' },
  { code: 'sd', name: 'Sindhi', nativeName: 'सिन्धी' },
  { code: 'se', name: 'Northern Sami', nativeName: 'Davvisámegiella' },
  { code: 'sg', name: 'Sango', nativeName: 'yângâ tî sängö' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල' },
  { code: 'sk', name: 'Slovak', nativeName: 'slovenčina', flag: '🇸🇰' },
  { code: 'sl', name: 'Slovene', nativeName: 'slovenščina', flag: '🇸🇮' },
  { code: 'sm', name: 'Samoan', nativeName: 'gagana faa Samoa' },
  { code: 'sn', name: 'Shona', nativeName: 'chiShona' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaaliga' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', flag: '🇦🇱' },
  { code: 'sr', name: 'Serbian', nativeName: 'српски језик', flag: '🇷🇸' },
  { code: 'ss', name: 'Swati', nativeName: 'SiSwati' },
  { code: 'st', name: 'Southern Sotho', nativeName: 'Sesotho' },
  { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda' },
  { code: 'sv', name: 'Swedish', nativeName: 'svenska', flag: '🇸🇪' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'tg', name: 'Tajik', nativeName: 'тоҷикӣ' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', flag: '🇹🇭' },
  { code: 'ti', name: 'Tigrinya', nativeName: 'ትግርኛ' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen' },
  { code: 'tl', name: 'Tagalog', nativeName: 'Tagalog' },
  { code: 'tn', name: 'Tswana', nativeName: 'Setswana' },
  { code: 'to', name: 'Tonga', nativeName: 'faka Tonga' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'ts', name: 'Tsonga', nativeName: 'Xitsonga' },
  { code: 'tt', name: 'Tatar', nativeName: 'татарча' },
  { code: 'tw', name: 'Twi', nativeName: 'Twi' },
  { code: 'ty', name: 'Tahitian', nativeName: 'Reo Tahiti' },
  { code: 'ug', name: 'Uighur', nativeName: 'Uyƣurqə' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'українська', flag: '🇺🇦' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'uz', name: 'Uzbek', nativeName: 'zbek' },
  { code: 've', name: 'Venda', nativeName: 'Tshivenḓa' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'vo', name: 'Volapük', nativeName: 'Volapük' },
  { code: 'wa', name: 'Walloon', nativeName: 'Walon' },
  { code: 'wo', name: 'Wolof', nativeName: 'Wollof' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Yorùbá' },
  { code: 'za', name: 'Zhuang', nativeName: 'Saɯ cueŋƅ' },
  { code: 'zh', name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu' },
] as const;

// Popular languages that should appear at the top of lists
export const popularLanguages = [
  'en',
  'es',
  'zh',
  'hi',
  'ar',
  'fr',
  'pt',
  'ru',
  'ja',
  'de',
  'ko',
  'it',
  'tr',
  'pl',
  'nl',
  'sv',
  'no',
  'da',
  'fi',
  'cs',
  'hu',
  'ro',
  'bg',
  'hr',
  'sr',
  'sk',
  'sl',
  'et',
  'lv',
  'lt',
] as const;

// Helper functions
export function getLanguageByCode(code: string): Language | undefined {
  return languages.find((lang) => lang.code === code);
}

export function getLanguageName(code: string, native = false): string {
  const language = getLanguageByCode(code);
  return language ? (native ? language.nativeName : language.name) : code;
}

export function getSortedLanguages(popularFirst = true): Language[] {
  if (!popularFirst) {
    return [...languages].sort((a, b) => a.name.localeCompare(b.name));
  }

  const popularSet = new Set(popularLanguages);
  const popular = languages.filter((lang) =>
    popularSet.has(lang.code as (typeof popularLanguages)[number]),
  );
  const rest = languages.filter(
    (lang) => !popularSet.has(lang.code as (typeof popularLanguages)[number]),
  );

  return [
    ...popular.sort((a, b) => a.name.localeCompare(b.name)),
    ...rest.sort((a, b) => a.name.localeCompare(b.name)),
  ];
}

export function searchLanguages(query: string): Language[] {
  const lowerQuery = query.toLowerCase();
  return languages.filter(
    (lang) =>
      lang.code.toLowerCase().includes(lowerQuery) ||
      lang.name.toLowerCase().includes(lowerQuery) ||
      lang.nativeName.toLowerCase().includes(lowerQuery),
  );
}
